### ISSUE TITLE
Package citation incorrect

### ISSUE THREAD

**Issue by justinkamerman** [justinkamerman/QFASA#3]
Hi Justin,
 
I have potentially another “issue” to add…  I want to cite the QFASA package in a paper that I am working on but when you use the command “citation”, currently what you get is simply the QFASA paper.  I don’t *think* this should be the same citation as the package.  (This is likely my fault…sorry).
 
When I use “citation” on another package (see below), the output is more in line with what I would expect to see.
 
Thanks!!
 
Connie
 
> citation("vegan")
 
To cite package ‘vegan’ in publications use:
 
  Jari Oksanen, F. Guillaume Blanchet, Michael Friendly, Roeland Kindt, Pierre Legendre, Dan McGlinn, Peter R. Minchin, R. B. O'Hara,
  Gavin L. Simpson, Peter Solymos, M. Henry H. Stevens, Eduard Szoecs and Helene Wagner (2017). vegan: Community Ecology Package. R
  package version 2.4-3. https://CRAN.R-project.org/package=vegan
 
A BibTeX entry for LaTeX users is
 
  @Manual{,
    title = {vegan: Community Ecology Package},
    author = {Jari Oksanen and F. Guillaume Blanchet and Michael Friendly and Roeland Kindt and Pierre Legendre and Dan McGlinn and Peter R. Minchin and R. B. O'Hara and Gavin L. Simpson and Peter Solymos and M. Henry H. Stevens and Eduard Szoecs and Helene Wagner},
    year = {2017},
    note = {R package version 2.4-3},
    url = {https://CRAN.R-project.org/package=vegan},
  }

**Comment by Gary3321** [comment]
fixed

**Comment by justinkamerman** [comment]
@cstewartGH what would you like the package citation to look like ? I'm sure Gary can work back from there and create a new citation file. I'm guessing something like this:

To cite package 'QFASA' in publications use:

Connie Stewart, ......... (2017)
QFASA: a super cool fatty acid package
package version 1.0.3  https://CRAN.R-project.org/package=QFASA

A BibTeX entry for LaTeX users is

@Manual{......

**Comment by cstewartGH** [comment]
Just talked to Hongchang and he explained this to me.  I believe the actual/new citation that you will now see (once this is on CRAN?) is correct (he showed it to me earlier this week), but just now pointed me to the description of the function citation().  In particular it says:

the function either returns the information contained in the ‘CITATION’ file of the package (using readCitationFile with meta equal to packageDescription(package, lib.loc)) or auto-generates citation information from the ‘DESCRIPTION’ file.

So my understanding is that we don’t need the citation file because the citation is coming from the description file.  Hongchang noticed that this was what was being done with the vegan package that I used as an example.

As long as we are not misunderstanding something, I think everything is good concerning the citation?

**Comment by justinkamerman** [comment]
Ah ok...that makes sense now...I did not know that :-$
